org.gradle.jvmargs=-Xmx4G -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.parallel=true

# Compose Multiplatform
kotlin.native.binary.objcExportInterfaceNamesPrefix=SMILE_

# Android
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.android.experimentalReferenceTracking=true

# Kotlin
kotlin.mpp.enableCInteropCommonization=true
