[versions]
kotlin = "2.1.0"
compose-multiplatform = "1.7.3"
compose-bom = "2024.12.01"
agp = "8.7.3"
sqldelight = "2.0.2"
camerax = "1.4.1"
workmanager = "2.10.0"
coroutines = "1.9.0"
lifecycle = "2.8.7"

[libraries]
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
compose-activity = { group = "androidx.activity", name = "activity-compose", version = "1.9.3" }
compose-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }

sqldelight-android-driver = { group = "app.cash.sqldelight", name = "android-driver", version.ref = "sqldelight" }
sqldelight-native-driver = { group = "app.cash.sqldelight", name = "native-driver", version.ref = "sqldelight" }
sqldelight-coroutines-ext = { group = "app.cash.sqldelight", name = "coroutines-extensions", version.ref = "sqldelight" }
sqldelight-runtime = { group = "app.cash.sqldelight", name = "runtime", version.ref = "sqldelight" }
sqldelight-primitive-adapters = { group = "app.cash.sqldelight", name = "primitive-adapters", version.ref = "sqldelight" }

mediapipe-tasks-vision = { group = "com.google.mediapipe", name = "tasks-vision", version = "0.10.18" }

camerax-core       = { group = "androidx.camera", name = "camera-core",       version.ref = "camerax" }
camerax-camera2    = { group = "androidx.camera", name = "camera-camera2",    version.ref = "camerax" }
camerax-lifecycle  = { group = "androidx.camera", name = "camera-lifecycle",  version.ref = "camerax" }
camerax-view       = { group = "androidx.camera", name = "camera-view",       version.ref = "camerax" }

workmanager-runtime = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workmanager" }

coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-android       = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose       = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
sqldelight           = { id = "app.cash.sqldelight", version.ref = "sqldelight" }
